export const SELLER_REGISTER = 'seller/register';
export const LOGIN='login';
export const ADD_PRODUCT = 'seller/add_product';
export const FETCH_PRODUCT='seller/fetch_product';
export const FETCH_BOOKING='fetch_booking/';
export const FETCH_BILL='fetch_bills/';
export const PREVIEW_BILL='seller/preview_bill/';
export const FETCH_SELLER_STATS='seller/fetch_seller_stats/';
export const CREATE_BILL='seller/create_bill/';
export const FETCH_BUYER_SELLER_RELATION='fetch_relation/';
export const ACCEPT_REJECT_BOOKING='seller/update_booking/';
export const ADD_FEEDBACK='add_feedback';
export const REGISTER_BUYER='buyer/register/';
export const CHECK_USER_EXIST ='is_exist/';
export const VERIFY_OTP ='otp_verify/';
export const ADD_DAILY_SALES ='seller/add_dailysales/';
export const ADD_BULK_DAILY_SALES ='seller/add_bulk_dailysales/';
export const CREATE_BILL_DISPIUTE ='buyer/add_billdispute/';

